site_name: pure_ocean_breeze documentation
site_url: https://chen-001.github.io/pure_ocean_breeze/
repo_url: https://github.com/chen-001/pure_ocean_breeze
nav:
    - 星空: index.md

    - 罗盘:

        - 状态&配置: 罗盘/state.md
        - 数据: 罗盘/data.md
        - 加工&测试&评价: 罗盘/labour.md

    - 火把: 
        - 项目: 火把/project.md
        - 构想&未来: 火把/futures.md
        - 分享: 火把/shares.md
        - 作者: 火把/author.md

theme:
  name: material
  language: 'zh'
  # locale: zh_CN
  analytics: {gtag: 'G-274394082'}
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js


extra:
  search:
    language: 'jp'