---
title: pure_ocean_breeze documentation
summary: python回测框架pure_ocean_breeze的说明文档
authors: 陈宗伟
date: 2022-08-14
some_url: 
    - https://github.com/chen-001/pure_ocean_breeze
    - https://pypi.org/project/pure-ocean-breeze/


site_name: pure_ocean_breeze documentation
nav:
    - 主页: index.md

    - 说明文档:

        - 状态&配置: 说明文档/state.md
        - 数据: 说明文档/data.md
        - 加工&测试&评价: 说明文档/labour.md

    - 关于: about.md

theme: 
    name: readthedocs
    titles_only: False
    locale: zh_CN

extra_css: [extra.css]