site_name: pure_ocean_breeze documentation
site_url: https://chen-001.github.io/pure_ocean_breeze/
nav:
    - 主页: index.md

    - 说明文档:

        - 状态&配置: 说明文档/state.md
        - 数据: 说明文档/data.md
        - 加工&测试&评价: 说明文档/labour.md

    - 关于: about.md

theme: 
    name: readthedocs
    titles_only: False
    locale: zh_CN

extra_css: [extra.css]