name: Deploy to Github Pages
on:
  push:
    # paths:
      # - docs/
      # - 'mkdocs.yml'
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material-zhcorrect
      - run: mkdocs build
      - run: mkdocs gh-deploy --force


