# 工作流的名称
name: publish site
# 在什么时候触发工作流
on:
  # 在从本地main分支被push到GitHub仓库时
  push:
    branches:
      - master
  # 在main分支合并别人提的pr时
  pull_request:
    branches:
      - master
# 工作流的具体内容
jobs:
  deploy:
    # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    runs-on: ubuntu-latest
    steps:
        # 先checkout到main分支
      - uses: actions/checkout@v2
        # 再安装Python3和相关环境
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
        # 使用pip包管理工具安装mkdocs-material
      - run: pip install mkdocs-material
        # 使用mkdocs-material部署gh-pages分支
      - run: mkdocs gh-deploy --force
