# action的名称
name: Upload Python Package

on:
  # 当setup.py分支有push时，触发action
  pull_request:

    paths:
      - "pure_ocean_breeze/__init__.py"
  
  push:
    
    paths:
      - "pure_ocean_breeze/__init__.py"

jobs:
  deploy:
    name: Upload to PyPI
    needs: [windows, linux, macos, sdist]
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
      
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: dist
          verbose: true